### ISSUE TITLE
Connexion3 Failed to load API definition in the Swagger UI

### ISSUE THREAD

**Issue by vladislavkoz** [spec-first/connexion#1829]
### Description
It works perfectly fine locally and it works fine during some time after deployment. But after some time returns 500 error code. API itself works fine and all end-points works fine. The issue with Swagger UI only. 
Before we added an exception handler we had just 500 error with the default message saying that something went wrong or app overloaded.
Now we use the following error_handler:
```
def connexion_base_exception_handler(
    request: ConnexionRequest, exc: Exception
) -> ConnexionResponse:
    return ConnexionResponse(
        status_code=500,
        body=json.dumps({"error": str(exc)}),
        content_type="application/json",
    )
```
As a result, str(exc) is actually openapi.json content

<img width="1496" alt="Screenshot 2023-12-06 at 09 36 49" src="https://github.com/spec-first/connexion/assets/40685761/d03f3bd6-fd80-46f6-a017-0122d422b54c">

### Expected behaviour
API definition loaded correctly

### Additional info:

Output of the commands:

- `python --version`  python:3.10
- `pip show connexion | grep "^Version\:"`. connexion[flask]==3.0.3
-  `starlette`. 0.33.0 or 0.32.0.post1

**Comment by nielsbox** [comment]
Have the same issue!

**Comment by vladislavkoz** [comment]
Fixed in 3.0.5. Thanks

**Comment by vladislavkoz** [comment]
@RDWimmers  I didn't try 3.2.0 so can't confirm this.

**Comment by wemcouncil** [comment]
I have run into the same issue, rolling back to 3.1.0 from 3.2.0 fixes the problem. If I have time, I will look into this tomorrow to see if I can find any clues.  Issue 2029 relevant for me as well

**Comment by tuomastik** [comment]
I can also confirm the issue is back with 3.2.0 and 3.1.0 fixes the problem.
